export const Users = [
  {
    id: 1,
    profilePicture: "assets/person/1.jpeg",
    username: "Trần Trí Thông",
  },
  {
    id: 2,
    profilePicture: "assets/person/2.jpeg",
    username: "Elon Musk",
  },
  {
    id: 3,
    profilePicture: "assets/person/3.jpeg",
    username: "Bill Gate",
  },
  {
    id: 4,
    profilePicture: "assets/person/4.jpeg",
    username: "Mark Zuckerberg",
  },
  {
    id: 5,
    profilePicture: "assets/person/5.jpeg",
    username: "Jeff Bezos",
  },
  {
    id: 6,
    profilePicture: "assets/person/6.jpeg",
    username: "Steve Jobs",
  },
  {
    id: 7,
    profilePicture: "assets/person/7.jpeg",
    username: "Donald Trump",
  },
  {
    id: 8,
    profilePicture: "assets/person/8.jpeg",
    username: "Joe Biden",
  },
  {
    id: 9,
    profilePicture: "assets/person/9.jpeg",
    username: "Barack Obama",
  },
  {
    id: 10,
    profilePicture: "assets/person/10.jpeg",
    username: "Cristiano Ronaldo",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Cùng học lập trình nào các bạn!!!",
    photo: "assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    heart: 0,
    comment: 9,
  },
  {
    id: 2,
    photo: "assets/post/2.jpeg",
    desc: "Chơi bitcoin không mấy em :)).",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    heart: 1,
    comment: 1,
  },
  {
    id: 3,
    desc: "Hôm nay tui buồn...",
    photo: "assets/post/3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    heart: 52,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/post/4.jpeg",
    desc: "Lướt ván không mấy bạn trẻ.",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    heart: 2,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/post/5.jpeg",
    desc: "Chuẩn bị bay lên mặt trăng thôi hihi.",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    heart: 12,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/post/6.jpeg",
    desc: "Mua Iphone giúp em đi quý dị.",
    date: "1 day ago",
    userId: 6,
    like: 44,
    heart: 62,
    comment: 6,
  },
  {
    id: 7,
    desc: "Mình thật là ngầu quá đi.",
    photo: "assets/post/7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    heart: 32,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/post/8.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    heart: 22,
    comment: 1,
  },
  {
    id: 9,
    desc: "Hôm nay thật vui.",
    photo: "assets/post/9.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    heart: 12,
    comment: 2,
  },
  {
    id: 10,
    photo: "assets/post/10.jpeg",
    desc: "Cảm thấy thất vọng...",
    date: "1 week ago",
    userId: 10,
    like: 104,
    heart: 100,
    comment: 12,
  },
];
